### ISSUE TITLE
Error: ./jill.sh: 23: "(" unexpected

### ISSUE THREAD

**Issue by richardkwo** [abelsiqueira/jill#2] opened 2018-03-17 00:35 UTC
./jill.sh: 23: ./jill.sh: Syntax error: "(" unexpected

**Comment by abelsiqueira** [comment] 2018-03-17 02:51
Could not reproduce. Did you use the command on the readme, or did you download and run? Could you try
```
sh jill.sh
```

**Comment by richardkwo** [comment] 2018-03-17 03:00
I did try this.

**Comment by richardkwo** [comment] 2018-03-23 22:20
`--version` not supported. I am using `/bin/sh` of Ubuntu 16.04.4 LTS

**Comment by abelsiqueira** [comment] 2018-03-25 13:01
Try `bash` instead of `sh`, please.

**Comment by abelsiqueira** [comment] 2018-03-26 11:11
I just confirmed that it should be `bash` instead of `sh` on Travis. On Arch Linux, `sh` is `bash` by default, so I missed that.

**Comment by richardkwo** [comment] 2018-03-26 19:03
Cool. Works on `bash`.

**Comment by abelsiqueira** [comment] 2018-03-26 19:05
Let me know if anything else breaks. Closing this one.

**Closed by abelsiqueira** 2018-03-26 19:05 UTC
